package ru.intech.ussd.modeler.entities;
// Generated 16.09.2015 10:30:26 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Actions generated by hbm2java
 */
@Entity
@Table(
		name = "actions")
public class Actions implements java.io.Serializable {
	private static final long serialVersionUID = 382451037762656729L;

	private int id;
	private String entryPointsSrv;
	private String dscr;
	private char akey;
	private int currentRoomId;
	private int nextRoomId;

	public Actions() {
	}

	public Actions(int id, String entryPointsSrv, char akey, int currentRoomId, int nextRoomId) {
		this.id = id;
		this.entryPointsSrv = entryPointsSrv;
		this.akey = akey;
		this.currentRoomId = currentRoomId;
		this.nextRoomId = nextRoomId;
	}

	public Actions(int id, String entryPointsSrv, String dscr, char akey, int currentRoomId, int nextRoomId) {
		this.id = id;
		this.entryPointsSrv = entryPointsSrv;
		this.dscr = dscr;
		this.akey = akey;
		this.currentRoomId = currentRoomId;
		this.nextRoomId = nextRoomId;
	}

	@Id
	@Column(
			name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(
			name = "entry_points_srv", nullable = false)
	public String getEntryPointsSrv() {
		return this.entryPointsSrv;
	}

	public void setEntryPointsSrv(String entryPointsSrv) {
		this.entryPointsSrv = entryPointsSrv;
	}

	@Column(
			name = "dscr")
	public String getDscr() {
		return this.dscr;
	}

	public void setDscr(String dscr) {
		this.dscr = dscr;
	}

	@Column(
			name = "akey", nullable = false, length = 1)
	public char getAkey() {
		return this.akey;
	}

	public void setAkey(char akey) {
		this.akey = akey;
	}

	@Column(
			name = "current_room_id", nullable = false)
	public int getCurrentRoomId() {
		return this.currentRoomId;
	}

	public void setCurrentRoomId(int currentRoomId) {
		this.currentRoomId = currentRoomId;
	}

	@Column(
			name = "next_room_id", nullable = false)
	public int getNextRoomId() {
		return this.nextRoomId;
	}

	public void setNextRoomId(int nextRoomId) {
		this.nextRoomId = nextRoomId;
	}

}
