package ru.intech.ussd.modeler.entities;
// Generated 16.09.2015 10:30:26 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EntryPoints generated by hbm2java
 */
@Entity
@Table(
		name = "entry_points")
public class EntryPoints implements java.io.Serializable {
	private static final long serialVersionUID = 2981082899869934613L;

	private int id;
	private String srv;
	private String dscr;
	private String msg;
	private int roomId;
	private Integer active;

	public EntryPoints() {
	}

	public EntryPoints(int id, String srv, String msg, int roomId) {
		this.id = id;
		this.srv = srv;
		this.msg = msg;
		this.roomId = roomId;
	}

	public EntryPoints(int id, String srv, String dscr, String msg, int roomId, Integer active) {
		this.id = id;
		this.srv = srv;
		this.dscr = dscr;
		this.msg = msg;
		this.roomId = roomId;
		this.active = active;
	}

	@Id
	@Column(
			name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(
			name = "srv", nullable = false)
	public String getSrv() {
		return this.srv;
	}

	public void setSrv(String srv) {
		this.srv = srv;
	}

	@Column(
			name = "dscr")
	public String getDscr() {
		return this.dscr;
	}

	public void setDscr(String dscr) {
		this.dscr = dscr;
	}

	@Column(
			name = "msg", nullable = false)
	public String getMsg() {
		return this.msg;
	}

	public void setMsg(String msg) {
		this.msg = msg;
	}

	@Column(
			name = "room_id", nullable = false)
	public int getRoomId() {
		return this.roomId;
	}

	public void setRoomId(int roomId) {
		this.roomId = roomId;
	}

	@Column(
			name = "active")
	public Integer getActive() {
		return this.active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}

}
